### PR TITLE
Move call to CreateTimeInterval

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

While looking at https://github.com/GEOS-ESM/MAPL/pull/1377 by @lizziel, it was found that her check was a bit too powerful for GEOS in that we have some bugs in our ExtData files. But, @bena-nasa looked at the code and found that we were doing `CreateTimeInterval` at the wrong time. Previously, we were doing it during the phase of ExtData when the *entire* `ExtData.rc` file is processed. Instead, we move the call to the loop where ExtData works on the actual Imports it will be handling.

@lizziel Can you make sure this change works with GCHP? I know it does with GEOS, but I decided to respect the process and make my PR on your branch and if you accept it, then it'll get pull to the mothership MAPL as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [ ] I have tested this change with a run of GCHP

### CODE REVIEW

**Comment by mathomp4** [comment]
I incorporated the Changelog change suggested by @tclune at https://github.com/GEOS-ESM/MAPL/pull/1377#discussion_r816142960

**Comment by lizziel** [comment]
Okay, I'll take a look.

**Comment by lizziel** [comment]
I can't tell just by looking so I'm doing a test run to be sure. I'll have an answer for you tomorrow.

**Comment by lizziel** [comment]
This was no diff for GCHP benchmark run so I merged it in.

**Pull request merged**
