### PR TITLE
Feature/v2.6.4

### PR DESCRIPTION
**Pull request by lizziel**
## Description
Update MAPL from 2.2.0 to 2.6.4. There is a separate PR for 2.5.0 from SDE and it is not yet decided whether we will go straight to 2.6.4 or do 2.5.0 first (3/23 update: This PR will supercede the one for 2.5.0). Regardless, looking at the merge changes for v2.6.4 and collaborating on the cmake updates in particular is useful. I committed the merge after handling conflicts and making several cmake file changes. The cmake files are very messy right now since I kept most of the merge conflict code to help with collaboration on the updates. This will need to be cleaned up and I'm seeking a review from @LiamBindle.

## How Has This Been Tested?
I built GCHP 13.0.0-rc.2 successfully from a 13.0.0-rc.2 run directory using gfortran 8.3.0 / OpenMPI 4.0.2. Note that I updated many other submodules and made a few code changes to do this. See the merge commit message from me on 3/19/21. More GCHP updates are needed to run successfully with this MAPL update. First I want to clean up the cmake code and make sure my work there is correct. Updates from SDE in a GCHP PR for MAPL 2.5 update should be usable with this MAPL update as well.

### CODE REVIEW

**Comment by lizziel** [comment]
For reference, the merge commit is here: https://github.com/geoschem/MAPL/commit/75ad85d440f55af10ad5b8aa7488463df443561d

The commit message explaining conflict resolution etc is:
```
This commit successfully compiles from a GCHP 13.0.0 run directory
if the gchp/main branches of the following submodules are checked out
manually (gchp/main as of today's date):
 1. all GFE libraries
 2. ESMA_cmake (do submodule update to get ecbuild updates)
 3. FVdycoreCubed_GridComp

Other necessary changes:
 1. Change MAPL use statement in GCHPctm.F90 to USE MAPL
 2. Apply FMS PR for MAPL 2.5 (not yet merged)

I handled the merge conflicts such that GCHP will compile with this
MAPL and these other modifications. However, I left most of the
merge conflict code and commented it out, adding notes on what I did.
More work is needed to clean this up and edit to follow standard
cmake best practices and fix any silent bugs. Work is also needed
for it to run within GCHP. A PR is open in GCHP with changes needed
beyond the GCHPctm.F90 code update to run (see SDE PR for MAPL 2.5 within
the GCHP repo).

# Conflicts: ( search for >> HEAD to see conflict res in progress, and
#              more generally search for GCHP to see areas changed )
#	CMakeLists.txt
#	MAPL/CMakeLists.txt
#	MAPL_cfio/CMakeLists.txt
#	base/CMakeLists.txt
#	base/MAPL_ExtDataGridCompMod.F90
#	pfio/CMakeLists.txt
#	shared/CMakeLists.txt
#	shared/MAPL_ErrorHandling.F90

# Also altered post-merge (search for GCHP in MAPL repo):
  generic/CMakeLists.txt
  gridcomps/Cap/CMakeLists.txt
  gridcomps/History/CMakeLists.txt
```

**Comment by LiamBindle** [comment]
@lizziel Thanks, I'll take a look at this on Wednesday. Is there a geoschem/GCHP branch that I could checkout and work from? You mention that there are other submodules with updates.

**Comment by lizziel** [comment]
Yes, I just pushed my GCHP development branch with submodule hashes for all the updated libraries. See branch `feature/gmao_library_updates`.

**Comment by lizziel** [comment]
Two edits are needed in this branch for GCHP to successfully run to completion. Both will no longer be necessary when this branch is ready to merge.

1. Comment out setting `cap_options%logger_config` in `GCHP.ctm.F90`. I am running into an error when using the `pFlogger` config file provided in PR https://github.com/geoschem/geos-chem/pull/595. It is possible the file worked for MAPL 2.5.0 but not 2.6.4. I will keep investigating for a fix.
2. Add the following paths to environment variable `LD_LIBRARY_PATH`, assuming you are running GCHP from a run directory with a subdirectory for the build. This is a temporary requirement until the build system is updated to put the shared libraries in a place made known to GCHP.
```
./build/src/MAPL/shared
./build/src/MAPL/gridcomps
./build/src/MAPL/profiler
```

**Comment by lizziel** [comment]
I ran a 1-month benchmark using GCHP 13.0.0 main and my feature/v2.6.4 branch. End-of-run global mass differences are at the level of numerical noise (<0.01%) for all species. Results are on the ftp site [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GCHPctm/13.1.0/mapl_v2.6.4/).

**Comment by lizziel** [comment]
This PR is now replaced with https://github.com/geoschem/MAPL/pull/7. It turns out that v2.6.4 is not yet used in GEOS and has bugs. We are going to update to v2.6.3 which is stable instead.

**Pull request closed without merging**
